spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/file_upload?characterEncoding=utf-8&allowLoadLocalInfile=true
    username: root
    password: yfs13981482985
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

logging:
  level:
    com:
      yang:
        fileUpload:
          mapper: ERROR